version: '3.3'

services:

  mysql_wp:
    image: mysql:5.7
    container_name: mysql_wp
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpresstroll:
    image: afornsv/fem-un-docker
    container_name: wordpress
    volumes:
      - wordpress_file:/var/www/html
    networks:
      - backend
      - frontend
    ports:
      - "8100:80"
    restart: always
    
volumes:
  wordpress_file: {}
  mysql_db: {}
networks:
  backend: {}
  frontend: {}

